myset: myset.o set.o
	gcc -g -ansi -Wall -pedantic myset.o set.o -o myset
myset.o: myset.c input.h
	gcc -c -ansi -Wall -pedantic myset.c -o myset.o
set.o: set.c set.h
	gcc -c -ansi -Wall -pedantic set.c -o set.o
	

